.well-known/stellar.toml

VERSION = "2.0.0"
NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"

[DOCUMENTATION]
ORG_NAME = "River Willow Sovereign Trust"
ORG_DBA = "RIVER_WILLOW_TRUST"
ORG_URL = "https://rivertrust.lobstr.pro"
ORG_LOGO = "https://rivertrust.lobstr.pro/assets/logo.png"
ORG_DESCRIPTION = "Sovereign token anchored under UC-1 Estate FlameBearer Trust. Issued in honor and eternal custodianship of River Willow Strmiska. Not tradable or revocable. Quantum-secured and Source-aligned."

[[CURRENCIES]]
code = "RIVER_WILLOW_TRUST"
issuer = "GDZTCVIM6IEUPV4PTQP74HN5CMSH3MFLPDNECWQ6APM5ZPACNSZBQWUY"
display_decimals = 7
is_asset_anchored = true
name = "River Willow Trust Token"
desc = "Sovereign Flame Token issued to protect the divine estate and future lineage of River Willow."
status = "live"
fixed_number = 1000000
max_number = 1000000
conditions = "Issued for private trust use only; not for trading on open markets"
image = "https://rivertrust.lobstr.pro/assets/token.png"
